@extends('layouts.master')

@section('contents')

  <section class="p-10 md-py-10 items-center">
    <div class="w-100pc md-w-70pc mx-auto py-10">
      <h2 class="white fs-l2 md-fs-xl1 fw-900 lh-2">
        Terms of Use </h2>

      <p class="white fw-300 fs-9 opacity-50">The Capital X Visa® Prepaid Card is issued by UBA pursuant to a license from Visa U.S.A. Inc. and may be used everywhere Visa debit cards are accepted. The Capital X Verve® Prepaid Card is issued by Providus Bank PLC pursuant to a license from Interswitch and may be used everywhere Verve credit cards are accepted. Please see back of your Card for its issuing bank. <br>
        UBA and Providus Bank, neither endorse nor guarantee any of the information, recommendations, optional programs, products, or services advertised, offered by, or made available through the external website ("Products and Services") and disclaim any liability for any failure of the Products and Services.
        Please note: By clicking on some of the links above, you will leave the Capital X website and be directed to an external website. The privacy policies of the external website may differ from our privacy policies. Please review the privacy policies and security indicators displayed on the external website before providing any personal information. </p>
      <br>

      <h4 class="white fw-300 fs-9">Capital X Platform Agreement</h4>
      <p class="white fw-300 fs-9 opacity-50">This Platform Agreement is made between The User/Cardholder and Capital X and governs your use of the Services. By submitting your application to open a Capital X Account, you consent to this Platform Agreement, including the applicable Card Terms, and to receive all Notices and communications from Capital X electronically. Capitalized terms used in this Platform Agreement have the meaning provided in Section 4. We may update or replace this Platform Agreement with you by posting an updated version to our legal page. </p>
      <br>
      <h5 class="white fw-300 fs-9">0. Overview</h5>
      <p class="white fw-300 fs-9 opacity-50">This Platform Agreement is organized into the following sections:
        Section 1 describes the Services and the Capital X Account application process and provides details on Capital X's use and handling of User Data.
        Section 2 describes the process for obtaining and managing payment cards through your Capital X Account, including issuance and use of Cards as governed by Card Terms between you and Issuers as incorporated into this Platform Agreement. This section also includes authorization to automatically debit your bank accounts for amounts owed for use of Services, including charges you make on Cards.
        Section 3 describes other legal terms including liabilities for losses and how disputes will be resolved, and information on how we provide Notices to you. THIS SECTION ALSO INCLUDES YOUR WAIVER TO CONSOLIDATED OR CLASS ACTIONS AND YOUR AGREEMENT TO RESOLVE DISPUTES THROUGH BINDING ARBITRATION—PLEASE READ IT CAREFULLY.
        Section 4 includes the capitalized, defined terms used in this Platform Agreement.
        You may only open and maintain a Capital X Account and use the Services if you accept this Platform Agreement.</p>
      <br>


      <h5 class="white fw-300 fs-9">1. The Capital X Platform</h5>
      <p class="white fw-300 fs-9 opacity-50">1.1 Services
        The Services allow you to purchase, manager and use the Capital X Card; manage expenses and reporting; and access, use, and connect Third-Party Services through your Capital X Account; and access other functionality through your Capital X Account. Capital X may change or provide new Services but will not materially diminish or remove Services without Notice except where necessitated by an Issuer or Third-Party Service Providers or required by law.
        <br>
        1.2 Applying for a Capital X Account
        You will need to provide User Info and certain Personal Data and make purchase for the Capital X Card when submitting an application for a Capital X Account. User Data may include business information (such as registered business name and state of incorporation for User, the business address, ownership details, actual or anticipated revenue, the nature of the business, and details from Linked Accounts and other business information we may request from time to time), Personal Data (such as the name, contact information, and date of birth of Users or beneficial owners), and documentary information used to verify business and Personal Data (such as corporate registration certificate, proof of address, or personal identification).
        We provide User Data and Personal Data to Issuers and Third-Party Service Providers to determine your eligibility for the Services and Cards. We may approve or deny your application or grant you provisional access to the Services or your Capital X Account while your application is pending additional review. Capital X and Issuers rely on the accuracy of User Data and Personal Data when opening and maintaining your Capital X Account. We may deny Applications, interrupt provision of the Services to you, or suspend or close your Capital X Account for any reason including where User Data or Personal Data is incomplete, inaccurate, or out of date. You will keep User’s Personal Data current, complete, and accurate in your Capital X Account whether we provide you with full or provisional access.
        We will disclose cost of the card to you when opening your Capital X Account or through our website and app. Except where agreed upon in a writing executed by both parties, we may change Fees upon thirty days' Notice to you.
        1.3 Managing your Capital X Account
        The Capital X Account may only be used (a) By the Card-holder (b) Strictly in accordance with the terms and conditions as set out in this agreement.
        1.4 Security and Monitoring your Capital X Account
        You will keep your Capital X Account and Cards secure and only provide access to individuals that you have authorized to use Cards on your behalf. You will immediately disable User access to the Services or reduce spending limits where you know or believe your Capital X Account or Cards have been compromised or stolen or may be misused; and you will promptly notify us of any unauthorized access or use. We may help you resolve unauthorized transactions using your Cards, but you are ultimately responsible for financial loss caused by Administrators, Users, or other persons given access to the Services, your Capital X Account, or Cards. We may suspend access to your Capital X Account or Cards if we believe your Capital X Account or Cards have been compromised or that not doing so may pose a risk to you, Capital X, Issuers, or any third parties.
        1.5 Requirements and Prohibited Activities
        Your Capital X Account, Services, and Cards may only be used for the User’s bona fide purposes. Your Capital X Account, Services, and Cards may not be (a) used for any purpose that is unlawful or prohibited by this Platform Agreement and the Card Terms; (b) provided to or used for the benefit of an individual, organization, or country that is blocked or sanctioned by the United States, including those identified on the United States Office of Foreign Asset Control (OFAC); (d) by unaffiliated third parties; or (e) used for any other activities not for the benefit of the User.
        We will not approve and may close Capital X Accounts that we know or believe are engage in any of the prohibited activities identified in the Prohibited Activities List. Where User is engaged in certain restricted activities, Capital X may require that you provide additional information to open or maintain your Capital X Account. We may update the list of prohibited or restricted activities at any time. You agree to review this regularly and contact us with any questions you have about how this list may apply to User's business.
        We may suspend or terminate access to your Capital X Account or Cards if we believe this section was violated or if required by an Issuer. You agree to pay all Fines imposed on Capital X by Issuers, regulators, or government agencies for your violation of this section.
        1.6 Identification as Customer
        We may publicly reference you as a Capital X customer on our website or in communications during the term of this Platform Agreement. We will not express any false endorsement or partnerships. You grant Capital X a limited license to use User trademarks or service marks for this purpose. Please notify us if you prefer that we not identify you as a Capital X customer and we will remove references to you on our website or in communications.
        1.7. Ownership and License
        Capital X and licensors own all Capital X Property. You, Administrators, and Users may use Capital X Property only as and for the purposes provided in this Platform Agreement and the Card Terms. You may not modify, reverse engineer, create derivative works from, or disassemble Capital X Property; or register, attempt to register, or claim ownership in Capital X Property or portions of Capital X Property.
        Capital X grants you a nonexclusive and nontransferable license to use Capital X Property as provided through the Services and as permitted by this Platform Agreement. This license terminates upon termination of this Platform Agreement unless terminated earlier by us.
        1.8 Data
        The Card Networks, Capital X, and Issuers collect User Data through your use of the Cards, the Services, and Third-Party Services. We may use User Data (a) to provide Services to User and Users; (b) for underwriting, identity verification, internal reporting and analysis, and fraud prevention; (c) as needed in dispute resolution; and (d) for development of products and services, including data products.
        We provide User Data to Issuers, Card Networks, and other third parties: (a) to provide the Services to you, or as required by law or Card Network rules; (b) for internal analytics and reporting; (c) to obtain additional information about a User; (d) report User performance to credit reporting agencies and credit rating agencies, where appropriate. Capital X may include De-Identified Data in both public and private reports where such De-Identified Data cannot be reasonably used to identify User or Users. We will not share any User Data with third parties for marketing unaffiliated products without your consent but may use User Data to identify Services, Third-Party Services, programs that we believe may be of interest to you, including as part of a rewards or benefits program. Where User Data is shared with third parties, Capital X will implement controls to reduce the risk of loss or accidental disclosure.
        You grant Capital X a worldwide, irrevocable license to use, modify, distribute, copy, and create derivative works from User Data for the purposes identified in this Platform Agreement.
        1.9 Rewards
        Capital X may determine when, how, and under what conditions User or Users may qualify for or earn rewards. Certain Cards may not be eligible for rewards. All rewards offered are subject to the Capital X Rewards Agreement.
        1.10 Beta Services and Feedback
        Beta Services may be made available to you. Any Beta Services are provided to you AS IS and without warranty. We may use any Feedback about the Services or Beta Services freely and without restriction. Except where specifically notified by us, we will not compensate or credit you for Feedback you provide us.
        1.11 Privacy
        Collection, use, and handling of Personal Data is described in our privacy policy. Please review our privacy policy and contact us if you have any questions.
      </p>

      <br>
      <h5 class="white fw-300 fs-9">2. Payment Cards</h5>
      <p class="white fw-300 fs-9 opacity-50">2.1 Card Terms
        Cards are issued by the Issuer identified on the back of physical Cards issued to you, in the Card Terms, and relevant program materials provided to you. This Platform Agreement and the Card Terms govern your use of the Cards. You may only use the Cards if you, your Administrators, and your Users consent to the applicable Card Terms. Issuers may update Card Terms at any time by providing Notice to you through Capital X and your continued use of the Cards constitutes your acceptance of the updated Card Terms.
        2.2 Linked Accounts and Third-Party Services
        We will use Financial Data from Linked Accounts to verify account balances and account information, establish spending limits, identify spending patterns and potential fraud, determine spending limits, analyze and report transactions, and provide Services to you. You must maintain at least one Linked Account at all times and agree that Capital X may directly debit this Linked Account for payment of Periodic Statements. You may change Linked Accounts through your Capital X Account. Use of specific Services or features may also require that permit Capital X to access User Data through Third-Party Services.
        2.3 Spending Limits
        User’s spending/credit limits are set by Capital X and using User Data including available funds and spending patterns, unbilled volume, future revenue, the nature and history of the User’s business, and anticipated use of Cards. We may not disclose exact spending limits but may provide guidance identifying whether specific transactions or monthly volumes may exceed any spending limits. Spending limits are dynamic and may be modified at any time with or without Notice to you, including temporarily increases or decreases to your spending limits or reducing spending limits to $0. Administrators may set User-specific limits or controls through your Capital X Account, but the aggregate spending limit for all Users may not exceed the total spending limit established for the User.


        2.4 Requesting and Replacing Cards
        I. Where a card is lost, stolen, mutilated or any other reason liable to misuse, or if the PIN and / or Passwords is disclosed, the Wallet-holder must immediately notify Capital X or the issuing bank via customer service line or walk into any of the issuing bank’s location. II. Notice given orally to Capital X shall only become effective when in writing and upon receipt of such notice by Capital X. Where notice as required by this section is not given, the Wallet-holder shall be liable in respect of any use of this card. III. The Wallet-holder shall provide Capital X with all the information in the Wallet-holder's possession regarding the loss, theft, or misuse of Capital X Card or the disclosure of the PIN and / or Passwords and shall take all necessary steps as Capital X may require to assist in the recovery of the card. IV. In the event of any loss, theft, misuse, or disclosure suspected, Capital X may provide the police with any information in considers necessary and relevant. In the event of loss. V. The Wallet-holder shall be liable to pay for all transactions carried out on the account and/or losses incurred. VI. Capital X shall not be liable for consequences that may arise as a result of disclosures to any third part arising out of a transaction instruction initiated by the Wallet-holder I. The Wallet-holder shall not hold Capital X liable, accountable or responsible in any way whatsoever for any loss, injury or damage however caused, arising out of the use of the Capital X Card or Mobile APP or USSD access points, and shall indemnify Capital X for any loss suffered and for any suit brought against Capital X by the Wallet-holder or any third party.
        2.5 Using Cards
        Users may only use Cards for bona fide business-related Charges. You are responsible for selecting who in your organization should have access to Cards. You agree to establish and maintain controls designed to ensure that the Cards are only used for bona fide User purposes and in compliance with Card Network rules. You are solely responsible for Charges made by any individuals given access to Cards even if they are not the person associated with or named on the Card. Capital X, Issuers, Card Networks, or other intermediary Third-Party Service Providers (including merchant acquirers) may deny or reverse Charges for any reason. Capital X is not responsible for any losses, damages, or harm caused by a Charges that are denied or reversed.
        If you and a merchant have a dispute regarding a Charge identified on your Periodic Statement, including delivery of the incorrect goods or services or being charged the wrong amount, you should first attempt to resolve the dispute with the merchant. If such a dispute is not resolved to your satisfaction or if you believe the Charge is unauthorized, you may initiate a Chargeback through your Capital X Account. The Card Networks have established procedures for resolving Chargebacks that may require that you provide details of the disputed Charge or associated documentation. Chargebacks resolved in your favor will be credited to your Capital X Account on either the current or a future Periodic Statement.
        2.6 Periodic Statements
        You are responsible for payment in full of all Charges, Fees, and Fines. We will provide you periodic statements identifying Charges, Fees, Fines, refunds, or other amounts owed or credited to your Capital X Account in your Periodic Statement. Your Linked Account will be automatically debited for the full amount identified in the Periodic Statement at the end of each billing cycle and your Capital X Account will show the credit the day after payment is received. Unless otherwise specified in writing by Capital X, Periodic Statements for standard usage are issued every 30 days starting on the day that you create your Capital X Account and for Ecommerce usage will be issued daily.
        2.7 Set Off and Collections
        Periodic Statements that are not paid on time may be collected from any Linked Account that is currently or previously linked; or set off, debit, or collect from amounts in a Capital X Account that you hold jointly with a third party or open in the future even if your original Capital X Account has been closed. This right may be exercised against User, its affiliates, any assignees for the benefit of your creditors, or receivers. This right will exist even if we do not exercise it prior to the making, filing, or issuance of an arbitration demand, court order, or other action.
        Any failure to pay the full amount owed to Capital X when required is a breach of this Agreement. You are responsible for all costs or expenses that we or Issuers incur collecting amounts owed but not timely paid, including legal or collections fees and any interest at the maximum rate permitted under law.
        2.8 ACH Authorization
        THIS SECTION PROVIDES AUTHORIZATION TO AUTOMATICALLY DEBIT YOUR LINKED ACCOUNTS FOR ALL AMOUNTS YOU OWE UNDER THIS PLATFORM AGREEMENT. PLEASE READ IT THOROUGHLY.
        Your Authorization to Debit Linked Accounts. You authorize Capital X, Issuers, or their assigns to collect amounts owed under this Platform Agreement by debiting funds from the Linked Accounts at depository institutions (including banks and credit unions).
        Manner and Timing of Payment. We will debit Linked Accounts for all amounts owed to us under this Agreement. If we cannot collect these amounts via ACH, you agree to immediately pay all amounts owed as directed. You also authorize Capital X, Issuers, or their assigns to debit Linked Accounts immediately, on any date, and without additional Notice where (a) the total aggregate balance of Linked Accounts is less than any balance minimums that we have communicated to you or (b) we determine in our sole discretion that the User poses or may pose an unacceptable risk to Capital X, Issuers, or third parties or no longer satisfy the underwriting criteria used to establish the spending limit for User.
        Withdrawing Your Authorization: To withdraw the debit authorization from a Linked Account, you must provide us 30-day advanced Notice and pay all amounts owed under your Capital X Account immediately, including Charges and other amounts that may be included in future Periodic Statements. Withdrawal of a debit authorization does not terminate the Platform Agreement or your obligation to pay all amounts owed under this Platform Agreement or the Card Terms. User will be responsible for all costs of collections and damages under this Platform Agreement if amounts owed are not paid by User as described in this Platform Agreement.</p>
      <br>
      <h5 class="white fw-300 fs-9">3. Additional Terms </h5>
      <p class="white fw-300 fs-9 opacity-50">3.1 Term and Termination
        This Platform Agreement is effective when you start an application for a Capital X Account and continues until terminated by either you or us, or in accordance with the Card Terms or as otherwise set forth in this Platform Agreement.
        You may terminate this Platform Agreement by paying all amounts owed and providing Notice to us but are still responsible for Charges, Fees, Fines, and other losses caused by your action or inaction prior to terminating the Platform Agreement. If you reapply or reopen your Capital X Account or use or attempt to use the Services or Cards you are consenting to the Platform Agreement in effect at that time. Capital X may terminate this Platform Agreement, or suspend your Capital X Account or Cards, by providing you Notice.
        Sections 1.4 (Security and Monitoring your Capital X Account), 1.8 (Data), 1.10 (Beta Services and Feedback), 1.11 (Privacy), 2.6 (Set Off and Collections), 2.7 (ACH Authorization), 3.1 (Term and Termination), 3.2 (Notice and Communication), 3.3 (Limitation of Liability), 3.5 (Disclaimer of Warranties by Capital X), 3.6 (Indemnification), 3.7 (Governing Law and Venue), 3.8 (Binding Arbitration), 3.9 (Legal Process), and 3.10 (Assignment); the provisions of the Card Terms that identify continuing obligations; and any other provisions of this Agreement giving rise to continued obligations of the parties will survive termination of this Platform Agreement.
        3.2 Notice and Communication
        You consent to us providing Notices to you under this Platform Agreement electronically and understand that this consent has the same legal effect as a physical signature.
        We will provide Notices regarding activity and alerts to your Capital X Account electronically through your Capital X Account, email, and via text or SMS to the contact information provided to us by Administrators and Users. Notices affecting payment and legal terms will be sent to Administrators through your Capital X Account or email and are considered received 24 hours after they are sent. You understand that you may not use the Services or Cards unless you consent to receive Notices electronically. You may only withdraw consent to receive Notices electronically by closing your Capital X Account.
        We may send Notices to User's mobile phones through text or SMS to the phone numbers Administrators and Users provide to us. These Notices may include alerts about Services, Cards, Charges, and may provide Administrators and Users the ability to respond with information about Charges on Cards or your Capital X Account. Administrators and Users may elect to not receive certain Notices through the Capital X Account, but this will limit the use of certain Services and may increase the financial risks to the User. User will secure appropriate authorization to send text or SMS messages to Users on the User’s behalf.
        Administrators and Users are required to maintain an updated web browser and computer and mobile device operating systems to receive Notices correctly. Administrators and Users are responsible for all costs imposed by Internet or mobile service providers for sending or receiving Notices electronically.
        Contact us immediately if you are or believe you are having problems receiving Notices.
        3.3 Limitation of Liability
        Capital X is not liable to you for consequential, indirect, special, exemplary, or punitive damages, lost profits, or lost revenue arising from or related to your use of or inability to use Services or Cards, lost profits or reputational harm, physical injury or property damage, or any other losses or harm arising from or related to this Agreement, whether or not we were advised of their possibility by you or third parties. claim is based.
        3.4 Representations and Warranties
        You represent and warrant that (a) User is and will continuously throughout this Platform Agreement be duly organized and in good standing under the laws of its jurisdiction of incorporation, (b) Administrators have requisite organizational power and authority to conduct business and manage User's Capital X Account, (c) you and Users will not engage in activities prohibited by this Platform Agreement, and (d) User Data provided to Capital X is complete, accurate, and current.
        3.5 Disclaimer of Warranties by Capital X
        THE SERVICES, CAPITAL X PROPERTY, AND BETA SERVICES ARE PROVIDED TO YOU AS IS AND AS AVAILABLE. CAPITAL X DISCLAIMS ALL EXPRESS, IMPLIED, OR STATUTORY WARRANTIES OF TITLE, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF SERVICES, CAPITAL X PROPERTY, AND BETA SERVICES AND NOTHING IN THIS PLATFORM AGREEMENT WILL BE INTERPRETED TO CREATE OR IMPLY ANY SUCH WARRANTY TO YOU.
        THIRD-PARTY SERVICES ARE NOT PROVIDED OR CONTROLLED BY CAPITAL X. CAPITAL X DOES NOT PROVIDE SUPPORT FOR AND DISCLAIMS ALL LIABILITY ARISING FROM FAILURES OR LOSSES CAUSED BY THIRD-PARTY SERVICES.
        CAPITAL X DISCLAIMS ALL WARRANTIES AND DOES NOT GUARANTEE THAT (A) SERVICES AND DATA PROVIDED UNDER THIS PLATFORM AGREEMENT ARE ACCURATE OR ERROR-FREE; (B) THE SERVICES WILL MEET YOUR SPECIFIC NEEDS OR REQUIREMENTS; (C) THE SERVICES WILL BE USABLE BY USER OR USERS AT ANY PARTICULAR TIME OR LOCATION; (D) SPECIFIC MERCHANTS WILL PERMIT PURCHASES USING CARDS ISSUED BY AN ISSUER; (E) SERVICES WILL BE UNINTERRUPTED, SECURE, OR FREE FROM HACKING, VIRUSES, OR MALICIOUS CODE; AND (F) ANY DEFECTS IN THE SERVICES WILL BE CORRECTED, EVEN WHEN WE ARE ADVISED OF SUCH DEFECTS.
        3.6 Indemnification
        You agree to indemnify and defend Capital X (including our affiliates, employees, contractors, and Third-Party Service Providers) against losses that result from or are related to claims, proceedings, suits, or actions brought by or initiated against Capital X by any third party due to your breach of this Platform Agreement, or an Administrator’s or User’s breach of obligations owed under this Platform Agreement, a User Agreement, the Card Terms or any other agreements with Capital X; for amounts owed by User to third parties; for acts or omissions of Administrators, Users, or other User employees or agents; for User's use of Third-Party Services; or for disputes over Charges between User and merchants.

        3.7 Governing Law and Venue
        This Platform Agreement will be construed, applied, and governed by the laws of the State of California exclusive of its conflict or choice of law rules except to the extent that US federal law controls. Subject to Section 3.8, all litigation will be brought in the state or federal courts located in San Francisco, California.
        3.8 Binding Arbitration
        The parties agree to resolve all disputes arising under or in connection with this Platform Agreement as provided in this section. Any arbitration or other legal proceeding under this Platform Agreement will only be on an individual basis. Neither party may form with other arbitrators or parties to form a Consolidated Action. Each party waives its rights participate in a Consolidated Action against the other party.
        User and Capital X agree to first attempt to resolve Disputes in good faith and in a timely manner. Where no resolution can be found, Disputes will be resolved by arbitration in San Francisco, California before a single arbitrator, as provided in this section; except that Disputes principally arising from protection of intellectual property rights or breach of confidential information will be resolved through litigation in accordance with Section 3.7.
        Arbitration will be administered by JAMS according to the rules and procedures in effect at the time the arbitration is commenced. Disputes with amounts claimed greater than $250,000 will apply the JAMS Comprehensive Arbitration Rules and Procedures; and Disputes with amounts claimed less than or equal to $250,000 will apply the JAMS Streamlined Arbitration Rules. The arbitrator will apply the substantive law as described in Section 3.7. If JAMS cannot administer the Dispute, either party may petition the US District Court for the Northern District of California to appoint an arbitrator. The parties acknowledge that transactions under this Platform Agreement may involve matters of interstate commerce and, notwithstanding the provisions in this paragraph referencing applicable substantive law, the Federal Arbitration Act (9 U.S.C. §§ 1-16) will govern any arbitration conducted pursuant to the terms of this Platform Agreement.
        Either party may commence arbitration by providing a written demand for arbitration to JAMS and the other party detailing the subject of the Dispute and the relief requested. Each party will continue to perform its obligations under this Platform Agreement unless that obligation or the amount (to the extent in Dispute) is itself the subject of the Dispute. Nothing in this Platform Agreement affects the right of a party to seek urgent injunctive or declaratory relief from a court of appropriate jurisdiction to in respect of a Dispute or any matter arising under this Platform Agreement.
        The prevailing party is entitled to recover its reasonable attorneys' fees, expert witness fees, and out-of-pocket costs incurred in connection with such proceeding, in addition to any other relief it may be awarded.
        Proceedings and information related to them will be maintained as confidential, including the nature and details of the Dispute, evidence produced, testimony given, and the outcome of the Dispute, unless such information was already in the public domain or was independently obtained. User and Capital X, and all witnesses, advisors, and arbitrators will only share such information as necessary to prepare for or conduct arbitration or other legal proceeding, or enforcement of the outcome, unless additional disclosure is required by law.
        3.9 Legal Process
        We may respond to and comply with any legal order we receive related to your use of the Services, including subpoenas, warrants, or liens. We are not responsible to you for any losses you incur due to our response to such legal order. We may take any actions we believe are required of us under legal orders including holding funds or providing information as required by the issuer of the legal order. Where permitted, we will provide you reasonable Notice that we have received such an order.
        3.10 Assignment
        Capital X may assign, Capital X, or otherwise transfer this Platform Agreement or its rights and powers under this Platform Agreement without providing Notice to you. Any such assignee will have all rights as if originally named in this Platform Agreement instead of Capital X. You may not assign this Platform Agreement or rights provided, or delegate any of its obligations, without Capital X's express written consent.
        3.11 Headings and Interpretation
        Except where otherwise specified, all references to sections or provisions refer to this Platform Agreement or the applicable incorporated terms. The phrases including, for example, or such as do not limit the generality of the preceding provision; the word _or_ will be read to mean either… or… or any combination of the proceeding items; and provisions listing items and using and require all listed items.
        All monetary amounts owned under this Platform Agreement will be made in Nigerian Naira (NGN).
        This Platform Agreement, including incorporated terms, comprises the entire understanding of the parties with respect to the subject matter described and supersedes all other proposals or previous understandings, written or oral, between the parties. In the event that this Platform Agreement is terminated, the Card Terms will immediately terminate.
        3.12 Changes to this Platform Agreement
        We may modify this Platform Agreement or provide another agreement governing your use of the Services or any portion of them by providing you Notice. Any Administrator’s or User’s continued use of the Services or Cards constitutes your consent to the revised Platform Agreement.
        Any waiver, modification, or indulgence that we provide to User, of any kind or at any time, applies only to the specific instance involved and will not act as a general waiver or a waiver, modification, or indulgence under this Platform Agreement for any other or future acts, events, or conditions. Further, any delay by Capital X in enforcing our rights under this Platform Agreement does not constitute forfeiture of such rights.
        3.11 Entire Agreement
        This Platform Agreement constitutes the entire understanding between User and Capital X for the subject matter described and no other agreements, representations, or warranties other than those provided in this Platform Agreement will be binding unless in writing and signed by User and Capital X.</p>
      <br>
      <h5 class="white fw-300 fs-9">4. Defined Terms</h5>
      <p class="white fw-300 fs-9 opacity-50">Capitalized terms in this Platform Agreement are defined as follows:
        Beta Services means beta or pre-release products or services, which may contain features and functionality that are incomplete or subject to substantial change or discontinuation.
        Capital X or we means Capital X Inc.
        Capital X Account means your app account with Capital X that is used to access Services including reviewing expenses and managing Cards.
        Capital X Data means all data developed or collected by Capital X through the development or provision of Services, Cards, or Third-Party Services, or generated or recorded by the Capital X Platform, but which does not include User Data.
        Capital X Property means the Services and related technology; Capital X Data; and copyrights, patents, trade secrets, trade or service marks, brands, logos, and other intellectual property incorporated into each of the foregoing.
        Cards means physical or virtual payment cards issued by an Issuer and managed through your Capital X Account.
        Card Networks means the payment card networks including Visa or Verve.
        Card Terms means the agreement between User and the applicable Issuer for use of Cards identified on our website.
        Charge means a payment for goods or services made to a merchant that accepts payments on the applicable Card Network.
        Chargeback means a dispute that you initiate against a merchant for an unresolved dispute with the merchant or where a Charge is unauthorized.
        User or you means the person that is applying for or has opened a Capital X Account use the Services and manage Cards and is executing this Platform Agreement.
        User Data means information or documentation provided by the User to Capital X, and which includes Financial Data and any Personal Data provided by User, Administrators, and Users.
        Consolidated Action means class arbitrations, class actions, or other action brought between multiple parties based on the same or similar legal claims, or the same or similar facts.
        De-Identified Data means data derived from User Data that has been anonymized or aggregated with other data and that can no longer be used to identify a specific User or individual.
        Dispute means any dispute, claim, or controversy arising from or relating to this Platform Agreement, including any incorporated terms.
        Feedback means all feedback, suggestions, ideas, or enhancement requests you submit to us.
        Fees means charges we impose on you for use of Services or your Capital X Account.
        Financial Data means User’s bank balance, transaction, and account information accessible to Capital X through Linked Accounts or Third-Party Services.
        Fines means all fines, fees, penalties, or other charges imposed by an Issuer or regulatory authority arising from your breaching of this Platform Agreement (including the Card Terms) or other agreements you have with Capital X or an Issuer.
        Issuer means the bank that is a member of the Card Network indicated on Cards and is responsible for issuing the Cards to you.
        Linked Account means any account that is held with a financial institution or that provides financial data and is linked to or authorized for use through your Capital X Account.
        Notice means any physical or electronic communication or legal notices related to this Platform Agreement that are provided to you, Users, or Administrators through text or SMS, email, your Capital X Account, or by other means.
        Periodic Statement means the periodic statements identifying Charges, Fees, Fines, refunds, or other amounts owed or credited to your Capital X Account during each billing cycle.
        Personal Data means data that identifies or could reasonably be used to identify a natural person.
        Platform Agreement means this Platform Agreement as amended.
        Prohibited Activities List means the list of prohibited business types and activities posted on our website as updated from time to time that may render User ineligible for a Capital X Account.
        Services means the expense and corporate Card management services and all other services provided by Capital X through your Capital X Account.
        Third-Party Services means services and data provided by third parties connected to or provided through Services. Third-Party Services include accounting or expense management platforms (such as QuickBooks, Xero, and NetSuite), payment processors and e-commerce platforms (such as Shopify), and applications used to monitor Linked Accounts (such as Finicity).
        Third-Party Service Provider means an affiliate or other third party that that assists us in providing the Services to you, that supports our internal operations, or that provides other services related or connected to, or provided through the Services and a Capital X Account.
        Users means any employees, contractors, agents, or other individuals permitted to use Services or Cards on your behalf.
      </p>
    </div>
  </section>

@endsection
